export const INJECTION_TOKENS = {
    USER_SERVICE_CLIENT:"USER_SERVICE_CLIENT",
    JWT_SERVICE_TOKEN:"JWT_SERVICE_TOKEN",

}

export const MESSAGE_PATTERN = {
    REGISTER_USER: "REGISTER_USER",
    LOGIN_USER: "LOGIN_USER",
}